CREATE TABLE BOOK(
			 B_Name VARCHAR(40) NOT NULL,
			 ISBN CHAR(10) NOT NULL,
			 Genre VARCHAR(20),
			 Author VARCHAR(20) NOT NULL,
			 Publisher VARCHAR(30) NOT NULL,
			 Price FLOAT(5,2) NOT NULL,
			 Location CHAR(2),
			 Award_winning CHAR(1),
			 PRIMARY KEY(ISBN),
			 UNIQUE(B_Name)
			 );

CREATE TABLE EMPLOYEE(
			 E_Fname VARCHAR(20) NOT NULL,
			 E_Lname VARCHAR(20) NOT NULL, 
			 Employee_ID INT(3),
			 Password VARCHAR(20) NOT NULL,
			 Position VARCHAR(20) NOT NULL,
			 PRIMARY KEY(Employee_ID)
			 );

CREATE TABLE CUSTOMER(
			 Username VARCHAR(20) NOT NULL,
			 Password VARCHAR(20) NOT NULL,
			 C_Fname VARCHAR(20),
			 C_Lname VARCHAR(20),
			 T_Rpoint INT NOT NULL,
			 Birthday DATE,
			 PRIMARY KEY(Username)
			 );

CREATE TABLE TRANSAC_B(
			 TB_num INT(10) NOT NULL,
			 B_price FLOAT(5,2) NOT NULL,
			 B_Date DATE NOT NULL,
			 E_ID INT(3),
			 Quantity INT NOT NULL,
			 ISBN VARCHAR(10) NOT NULL,
			 PRIMARY KEY(TB_num),
			 FOREIGN KEY(E_ID) REFERENCES EMPLOYEE(Employee_ID)
			 	ON DELETE SET NULL ON UPDATE CASCADE,
			 FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
			 	ON DELETE NO ACTION ON UPDATE CASCADE
			 );

CREATE TABLE TRANSAC_S(
			 TS_num INT(10) NOT NULL,
			 R_point INT NOT NULL,
			 S_price FLOAT(5,2) NOT NULL,
			 S_Date DATE NOT NULL,
			 C_name VARCHAR(20),
			 E_ID INT(3),
			 Quantity INT(10) NOT NULL,
			 ISBN VARCHAR(10) NOT NULL,
			 PRIMARY KEY(TS_num),
			 FOREIGN KEY(C_name) REFERENCES CUSTOMER(Username) 
			 	ON DELETE SET NULL ON UPDATE CASCADE,
			 FOREIGN KEY(E_ID) REFERENCES EMPLOYEE(Employee_ID) 
			 	ON DELETE SET NULL ON UPDATE CASCADE, 
			 FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) 
			 	ON DELETE NO ACTION ON UPDATE CASCADE
 			 );

CREATE TABLE INVENTORY(
			 ISBN VARCHAR(10) NOT NULL,
			 Quantity INT NOT NULL,
			 PRIMARY KEY(ISBN),
			 FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
			 	ON DELETE CASCADE ON UPDATE CASCADE
			 );